language: ruby
rvm:
  - 2.4.1

before_script:
  - psql -c 'create database indyhackers_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test

env:
  - DB=postgresql
