defaults: &defaults
  adapter: postgresql
  host: localhost
  username: mileszs
  password:

development:
  database: indyhackers_dev
  <<: *defaults

test: &TEST
  database: indyhackers_test
  <<: *defaults

production:
  database: indyhackers_dev
  <<: *defaults

cucumber:
  <<: *TEST
